services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
     - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    
  db:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}   
      MYSQL_DATABASE: ${DB_NAME}  
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: